version: 2
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/sops-sakura-kms/
    binary: sops-sakura-kms
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
release:
  use_existing_draft: true
checksum:
  name_template: "checksums.txt"
archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
